version: "3.9"
services:
 frontend:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: frontend-app
   restart: always
   ports:
     - 8080:8000
   volumes:
     - ./frontend:/opt/app
     - /app/node_modules
   environment:
     - VITE_APP_BACKEND_ADDRESS=http://localhost/api