# Generated by Django 5.1.2 on 2024-10-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='left_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner_amount',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='users_involved',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
