# Generated by Django 5.1.2 on 2024-11-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owing',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
