# Generated by Django 5.1.2 on 2024-10-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_group_left_users_alter_group_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='groups_joined',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
