# Generated by Django 5.1.2 on 2024-11-03 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_owing_is_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
