# Generated by Django 5.1.2 on 2024-11-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_bill_created_at_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
