# Generated by Django 5.1.2 on 2024-11-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_rename_owing_owning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
    ]
