# Generated by Django 5.1.2 on 2024-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_groupinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.DeleteModel(
            name='GroupInvitation',
        ),
    ]
