# Generated by Django 5.1.2 on 2024-11-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_transaction_bill'),
        ('billing', '0009_appuser_first_name_appuser_image_appuser_last_name'),
    ]

    operations = [
    ]
